spring:
  application:
    name: transaction
  datasource:
    initialize: true
    url: jdbc:h2:mem:inventory;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  openfeign:
    client:
      config:
        testClient:
          url: